"use client";
import { motion } from "framer-motion";
import { ArrowRight, CalendarDays, Dumbbell, Flame, Instagram, MapPin, Menu, MessageCircle, Trophy, Users, X } from "lucide-react";
import { useState } from "react";

const programs=[["Strength","Build measurable strength with progressive training.","Dumbbell"],["HIIT","High-intensity conditioning built for serious results.","Flame"],["Boxing","Sharpen technique, footwork and fight-ready conditioning.","Trophy"],["Personal Training","One-to-one coaching around your goals.","Users"]];
const classes=[["FORGE STRENGTH","Mon · 6:00 PM","Advanced"],["IRON HIIT","Tue · 7:00 AM","Intermediate"],["BOXING CONDITIONING","Thu · 6:30 PM","All Levels"],["PERFORMANCE LAB","Sat · 9:00 AM","Advanced"]];
export default function Home(){
 const [open,setOpen]=useState(false);
 return <main>
  <nav className="nav"><a className="logo" href="#">IRON<span>FORGE</span><small>ATHLETICS</small></a><div className={open?"links open":"links"}>{["About","Programs","Classes","Trainers","Membership","Facilities","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}<a className="navCta" href="#membership">JOIN NOW <ArrowRight size={16}/></a></div><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></nav>
  <section className="hero"><div className="heroShade"/><div className="heroContent"><p className="eyebrow">STRENGTH · PERFORMANCE · DISCIPLINE</p><h1>BUILD YOUR<br/><i>STRONGEST</i> SELF.</h1><p className="lead">Train with purpose. Move with power. Become the version of yourself that refuses to settle.</p><div className="actions"><a className="btn primary" href="#membership">START TRAINING <ArrowRight size={18}/></a><a className="btn ghost" href="#programs">EXPLORE PROGRAMS</a></div></div><div className="heroStat"><strong>24/7</strong><span>ACCESS AVAILABLE</span></div></section>
  <section className="ticker"><span>NO EXCUSES</span><span>PROGRESSIVE TRAINING</span><span>EXPERT COACHING</span><span>REAL RESULTS</span></section>
  <section id="programs" className="section"><div className="sectionHead"><div><p className="eyebrow">01 / TRAINING</p><h2>FORGE YOUR <i>EDGE.</i></h2></div><a className="textLink" href="#classes">VIEW ALL PROGRAMS <ArrowRight size={16}/></a></div><div className="grid4">{programs.map(([title,desc,icon],i)=><motion.article whileHover={{y:-8}} className="card" key={title}><span className="num">0{i+1}</span><div className="icon">{icon==="Flame"?<Flame/>:icon==="Trophy"?<Trophy/>:icon==="Users"?<Users/>:<Dumbbell/>}</div><h3>{title}</h3><p>{desc}</p><a href="#contact">LEARN MORE <ArrowRight size={15}/></a></motion.article>)}</div></section>
  <section id="about" className="split"><div className="photo aboutPhoto"/><div className="darkPanel"><p className="eyebrow">02 / THE IRONFORGE METHOD</p><h2>TRAIN HARD.<br/><i>TRAIN SMART.</i></h2><p>IRONFORGE is built around structured programming, expert coaching and a community that takes progress seriously.</p><div className="stats"><div><b>20+</b><span>EXPERT COACHES</span></div><div><b>50+</b><span>WEEKLY CLASSES</span></div><div><b>5K+</b><span>MEMBER STORIES</span></div></div><a className="btn primary" href="#contact">MEET THE TEAM <ArrowRight size={18}/></a></div></section>
  <section id="classes" className="section"><div className="sectionHead"><div><p className="eyebrow">03 / THIS WEEK</p><h2>CLASS <i>LINEUP.</i></h2></div><a className="textLink" href="#contact">BOOK A CLASS <CalendarDays size={16}/></a></div><div className="classList">{classes.map((c,i)=><div className="classRow" key={c[0]}><span className="classNum">0{i+1}</span><div><h3>{c[0]}</h3><p>{c[1]}</p></div><span className="level">{c[2]}</span><a href="#contact"><ArrowRight/></a></div>)}</div></section>
  <section id="membership" className="membership"><div><p className="eyebrow">04 / MEMBERSHIP</p><h2>CHOOSE YOUR<br/><i>FORGE.</i></h2><p>Flexible access. Serious training. One standard: progress.</p></div><div className="plans">{[["FORGE","₦35,000","Gym access · Classes · App"],["ELITE","₦60,000","Full access · All classes · Recovery"],["PERFORMANCE","₦120,000","Elite · 4 PT sessions · Priority booking"]].map((p,i)=><div className={i===1?"plan featured":"plan"} key={p[0]}><span>{p[0]}</span><strong>{p[1]}<small>/ MONTH</small></strong><p>{p[2]}</p><a className="btn primary" href="#contact">JOIN {p[0]}</a></div>)}</div></section>
  <section id="contact" className="contact"><div><p className="eyebrow">05 / GET STARTED</p><h2>READY TO<br/><i>FORGE?</i></h2><p>Come in for a tour, talk to a coach, and build your training plan.</p><a className="btn primary" href="https://wa.me/" target="_blank">CHAT ON WHATSAPP <MessageCircle size={18}/></a></div><div className="contactBox"><div><MapPin/><span>LAGOS, NIGERIA<br/><small>ADDRESS TO BE CONFIGURED</small></span></div><div><CalendarDays/><span>MON–SUN<br/><small>OPENING HOURS TO BE CONFIGURED</small></span></div><div><Instagram/><span>FOLLOW THE FORGE<br/><small>@IRONFORGEATHLETICS</small></span></div></div></section>
  <footer><a className="logo" href="#">IRON<span>FORGE</span><small>ATHLETICS</small></a><p>© 2026 IRONFORGE ATHLETICS. ALL RIGHTS RESERVED.</p><div><a href="#">Privacy</a><a href="#">Terms</a></div></footer>
 </main>
}