import { createClient } from "../../../lib/supabase/server";
import { redirect } from "next/navigation";
import { savePlan,deletePlan,saveTrainer,deleteTrainer,saveClass,deleteClass,updateBooking,updateMessage,updateTrainingRequest,checkInMember } from "../actions";

export default async function ManagementPage(){
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 if(!user) redirect("/login");
 const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();
 if(profile?.role!=="admin") redirect("/member");
 const [{data:plans},{data:trainers},{data:classes},{data:bookings},{data:messages},{data:requests},{data:members},{data:attendance}]=await Promise.all([
  supabase.from("membership_plans").select("*").order("price_ngn"),
  supabase.from("trainers").select("*").order("name"),
  supabase.from("classes").select("*,trainers(name)").order("day_of_week").order("start_time"),
  supabase.from("class_bookings").select("id,status,booked_at,profiles(full_name,email),classes(name)").order("booked_at",{ascending:false}).limit(50),
  supabase.from("contact_messages").select("*").order("created_at",{ascending:false}).limit(50),
  supabase.from("personal_training_requests").select("*").order("created_at",{ascending:false}).limit(50),
  supabase.from("profiles").select("id,full_name").eq("role","member").order("full_name"),
  supabase.from("attendance").select("id,user_id,class_id,checked_in_at,profiles(full_name),classes(name)").order("checked_in_at",{ascending:false}).limit(50)
 ]);
 const field=(name:string,value?:string|number)=> <input name={name} defaultValue={value??""} required className="adminInput"/>;
 return <main className="page adminPage"><a className="back" href="/admin">← ADMIN</a><p className="eyebrow">IRONFORGE / MANAGEMENT</p><h1>OPERATIONS <i>CONTROL.</i></h1>
 <section className="adminSection"><h2>MEMBERSHIP PLANS</h2><div className="adminCards">{plans?.map(p=><div className="adminCard" key={p.id}><form action={savePlan}>{field("id",p.id)}{field("name",p.name)}{field("price_ngn",p.price_ngn)}{field("billing_period",p.billing_period)}{field("description",p.description)}<label><input type="checkbox" name="active" defaultChecked={p.active}/> Active</label><button className="btn" type="submit">SAVE</button></form><form action={deletePlan}><input type="hidden" name="id" value={p.id}/><button className="btn btnGhost">DEACTIVATE</button></form></div>)}<form action={savePlan} className="adminCard"><h3>NEW PLAN</h3>{field("name")}{field("price_ngn")} {field("billing_period","monthly")}{field("description")}<label><input type="checkbox" name="active" defaultChecked/> Active</label><button className="btn" type="submit">CREATE PLAN</button></form></div></section>
 <section className="adminSection"><h2>TRAINERS</h2><div className="adminCards">{trainers?.map(t=><div className="adminCard" key={t.id}><form action={saveTrainer}>{field("id",t.id)}{field("name",t.name)}{field("specialty",t.specialty)}{field("bio",t.bio)}{field("image_url",t.image_url||"")}<label><input type="checkbox" name="active" defaultChecked={t.active}/> Active</label><button className="btn" type="submit">SAVE</button></form><form action={deleteTrainer}><input type="hidden" name="id" value={t.id}/><button className="btn btnGhost">DEACTIVATE</button></form></div>)}<form action={saveTrainer} className="adminCard"><h3>NEW TRAINER</h3>{field("name")}{field("specialty")}{field("bio")}{field("image_url")}<label><input type="checkbox" name="active" defaultChecked/> Active</label><button className="btn" type="submit">CREATE TRAINER</button></form></div></section>
 <section className="adminSection"><h2>CLASSES</h2><div className="adminCards">{classes?.map(c=><div className="adminCard" key={c.id}><form action={saveClass}>{field("id",c.id)}{field("name",c.name)}{field("description",c.description)}{field("day_of_week",c.day_of_week)}{field("start_time",c.start_time)}{field("duration_minutes",c.duration_minutes)}{field("capacity",c.capacity)}<select name="trainer_id" className="adminInput"><option value="">No trainer</option>{trainers?.map(t=><option key={t.id} value={t.id} selected={t.id===c.trainer_id}>{t.name}</option>)}</select><label><input type="checkbox" name="active" defaultChecked={c.active}/> Active</label><button className="btn" type="submit">SAVE</button></form><form action={deleteClass}><input type="hidden" name="id" value={c.id}/><button className="btn btnGhost">DEACTIVATE</button></form></div>)}<form action={saveClass} className="adminCard"><h3>NEW CLASS</h3>{field("name")}{field("description")}{field("day_of_week",1)}{field("start_time","09:00")}{field("duration_minutes",60)}{field("capacity",20)}<select name="trainer_id" className="adminInput"><option value="">No trainer</option>{trainers?.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><label><input type="checkbox" name="active" defaultChecked/> Active</label><button className="btn" type="submit">CREATE CLASS</button></form></div></section>
 <section className="adminSection"><h2>ATTENDANCE / CHECK-IN</h2><div className="adminCards"><form action={checkInMember} className="adminCard"><h3>CHECK IN MEMBER</h3><select name="user_id" className="adminInput" required><option value="">Select member</option>{members?.map((m:any)=><option key={m.id} value={m.id}>{m.full_name||"Unnamed member"}</option>)}</select><select name="class_id" className="adminInput"><option value="">General gym visit</option>{classes?.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="btn" type="submit">CHECK IN</button></form><div className="adminCard"><h3>RECENT CHECK-INS</h3>{attendance?.slice(0,12).map((a:any)=>{const m=Array.isArray(a.profiles)?a.profiles[0]:a.profiles;const cls=Array.isArray(a.classes)?a.classes[0]:a.classes;return <div className="adminRow" key={a.id}><span><strong>{m?.full_name||"Member"}</strong> — {cls?.name||"Gym visit"}<br/>{new Date(a.checked_in_at).toLocaleString()}</span></div>})}</div></div></section>
 <section className="adminSection"><h2>BOOKINGS</h2>{bookings?.map(b=><div className="adminRow" key={b.id}><span>{((b.classes as any)?.[0]?.name ?? (b.classes as any)?.name)||"Class"} — {((b.profiles as any)?.[0]?.full_name ?? (b.profiles as any)?.full_name)||"Member"} — {b.status}</span><form action={updateBooking}><input type="hidden" name="id" value={b.id}/><select name="status" defaultValue={b.status}><option>confirmed</option><option>cancelled</option></select><button className="btn" type="submit">UPDATE</button></form></div>)}</section>
 <section className="adminSection"><h2>CONTACT ENQUIRIES</h2>{messages?.map(m=><div className="adminRow" key={m.id}><span><strong>{m.name}</strong> — {m.subject||"General"} — {m.status}<br/>{m.message}</span><form action={updateMessage}><input type="hidden" name="id" value={m.id}/><select name="status" defaultValue={m.status}><option>new</option><option>read</option><option>resolved</option></select><button className="btn" type="submit">UPDATE</button></form></div>)}</section>
 <section className="adminSection"><h2>PERSONAL TRAINING REQUESTS</h2>{requests?.map(r=><div className="adminRow" key={r.id}><span><strong>{r.name}</strong> — {r.preferred_time||"Flexible"} — {r.status}<br/>{r.goals}</span><form action={updateTrainingRequest}><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status}><option>new</option><option>contacted</option><option>scheduled</option><option>closed</option></select><button className="btn" type="submit">UPDATE</button></form></div>)}</section>
 </main>
}